services:
  - type: web
    name: seeker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
