# Generated by Django 5.2.3 on 2025-06-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interest_customuser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
