# Generated by Django 5.2.3 on 2025-06-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interest_icon_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='icon_path',
            new_name='icon_name',
        ),
    ]
