# Generated by Django 5.2.3 on 2025-06-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_icon_path_interest_icon_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='myjobs_ge',
        ),
    ]
